// <auto-generated />
using CampusCoin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CampusCoin.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260928120000_AddBookmarkSnapshotColumns")]
    partial class AddBookmarkSnapshotColumns
    {
    }
}
